### PR TITLE
Chore/update zbus

### PR DESCRIPTION
**Pull request by hunjixin**
@frewsxcv  please check this ,but ``` reply.body().deserialize::<u32>();```` fail on ubuntu, i am sure this work as expected

### CODE REVIEW

**Comment by frewsxcv** [comment]
I don't have a Linux machine to test this

**Comment by frewsxcv** [comment]
@Be-ing and @edfloreshz might have thoughts about this

**Comment by hunjixin** [comment]
yea i see https://github.com/frewsxcv/rust-dark-light/pull/31 but this is opened last month. any way to test this?

**Comment by edfloreshz** [comment]
I'm currently on vacation, once I return home I will take a look :)

**Comment by Be-ing** [comment]
thanks

**Comment by Be-ing** [comment]
@frewsxcv publish a 1.1 release?

**Comment by frewsxcv** [comment]
Yep will push a release right now

**Comment by frewsxcv** [comment]
Done

**Pull request merged**
